-- ==============================================================================
-- TimePulse Time & Attendance System - Consolidated Schema & Seed Data
-- Automatically executed on Docker container startup (/docker-entrypoint-initdb.d)
-- ==============================================================================

CREATE DATABASE IF NOT EXISTS `timeclock_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `timeclock_db`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


-- 1. Departments table
CREATE TABLE IF NOT EXISTS `departments` (
  `dept_id` INT NOT NULL,
  `dept_name` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Employees table
CREATE TABLE IF NOT EXISTS `employees` (
  `user_id` INT NOT NULL,
  `badge_number` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` VARCHAR(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gender` VARCHAR(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dept_id` INT DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  KEY `idx_dept` (`dept_id`),
  CONSTRAINT `fk_emp_dept` FOREIGN KEY (`dept_id`) REFERENCES `departments` (`dept_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Clock Devices table
CREATE TABLE IF NOT EXISTS `devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sn` VARCHAR(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `alias` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_address` VARCHAR(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location` VARCHAR(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `model` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_master` TINYINT(1) NOT NULL DEFAULT '0',
  `status` ENUM('active','inactive') COLLATE utf8mb4_unicode_ci DEFAULT 'active',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sn` (`sn`),
  KEY `idx_sn` (`sn`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Attendance punches table
CREATE TABLE IF NOT EXISTS `checkinout` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `check_time` DATETIME NOT NULL,
  `check_type` VARCHAR(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `normalized_type` ENUM('in','out') COLLATE utf8mb4_unicode_ci NOT NULL,
  `sensor_id` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `work_code` INT DEFAULT '0',
  `sn` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_checktime` (`user_id`,`check_time`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_check_time` (`check_time`),
  KEY `idx_user_time` (`user_id`,`check_time`),
  KEY `idx_norm_type` (`normalized_type`),
  CONSTRAINT `fk_punch_emp` FOREIGN KEY (`user_id`) REFERENCES `employees` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Sync audit log
CREATE TABLE IF NOT EXISTS `sync_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sync_start` DATETIME NOT NULL,
  `sync_end` DATETIME DEFAULT NULL,
  `records_read` INT DEFAULT '0',
  `records_inserted` INT DEFAULT '0',
  `status` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT 'SUCCESS',
  `error_message` TEXT COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. Application Users (authentication & authorization)
CREATE TABLE IF NOT EXISTS `app_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_name` VARCHAR(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` ENUM('admin','viewer') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'viewer',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. User Sessions
CREATE TABLE IF NOT EXISTS `sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `idx_token` (`token`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `fk_sess_user` FOREIGN KEY (`user_id`) REFERENCES `app_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Employee Leaves table
CREATE TABLE IF NOT EXISTS `leaves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `leave_type_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `notes` TEXT COLLATE utf8mb4_unicode_ci,
  `status` ENUM('pending','approved','rejected') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `submitted_by_self` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_dates` (`start_date`,`end_date`),
  CONSTRAINT `fk_leave_emp` FOREIGN KEY (`user_id`) REFERENCES `employees` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 9. Biometric Fingerprint Templates
CREATE TABLE IF NOT EXISTS `biometric_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `uid` INT NOT NULL,
  `finger_id` TINYINT NOT NULL,
  `valid_flag` TINYINT NOT NULL DEFAULT '1',
  `template_size` INT NOT NULL,
  `template_data` MEDIUMBLOB NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_uid_fid` (`uid`,`finger_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Legacy and Extended Compatibility Tables
-- Complete Schema for TimeClock Attendance System (All Tables)
-- Auto-generated from att2000.mdb and TimePulse application



CREATE TABLE IF NOT EXISTS `ACGroup` (
  `GroupID` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `TimeZone1` INT DEFAULT NULL,
  `TimeZone2` INT DEFAULT NULL,
  `TimeZone3` INT DEFAULT NULL,
  `holidayvaild` TINYINT(1) DEFAULT NULL,
  `verifystyle` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `acholiday` (
  `primaryid` BIGINT DEFAULT NULL,
  `holidayid` BIGINT DEFAULT NULL,
  `begindate` DATETIME DEFAULT NULL,
  `enddate` DATETIME DEFAULT NULL,
  `timezone` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ACTimeZones` (
  `TimeZoneID` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `SunStart` DATETIME DEFAULT NULL,
  `SunEnd` DATETIME DEFAULT NULL,
  `MonStart` DATETIME DEFAULT NULL,
  `MonEnd` DATETIME DEFAULT NULL,
  `TuesStart` DATETIME DEFAULT NULL,
  `TuesEnd` DATETIME DEFAULT NULL,
  `WedStart` DATETIME DEFAULT NULL,
  `WedEnd` DATETIME DEFAULT NULL,
  `ThursStart` DATETIME DEFAULT NULL,
  `ThursEnd` DATETIME DEFAULT NULL,
  `FriStart` DATETIME DEFAULT NULL,
  `FriEnd` DATETIME DEFAULT NULL,
  `SatStart` DATETIME DEFAULT NULL,
  `SatEnd` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ACUnlockComb` (
  `UnlockCombID` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Group01` INT DEFAULT NULL,
  `Group02` INT DEFAULT NULL,
  `Group03` INT DEFAULT NULL,
  `Group04` INT DEFAULT NULL,
  `Group05` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AlarmLog` (
  `ID` BIGINT DEFAULT NULL,
  `Operator` VARCHAR(255) DEFAULT NULL,
  `EnrollNumber` VARCHAR(255) DEFAULT NULL,
  `LogTime` DATETIME DEFAULT NULL,
  `MachineAlias` VARCHAR(255) DEFAULT NULL,
  `AlarmType` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AuditedExc` (
  `AEID` BIGINT DEFAULT NULL,
  `UserId` BIGINT DEFAULT NULL,
  `CheckTime` DATETIME DEFAULT NULL,
  `NewExcID` BIGINT DEFAULT NULL,
  `IsLeave` INT DEFAULT NULL,
  `UName` VARCHAR(255) DEFAULT NULL,
  `UTime` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AUTHDEVICE` (
  `ID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `MachineID` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `CHECKEXACT` (
  `EXACTID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `CHECKTIME` DATETIME DEFAULT NULL,
  `CHECKTYPE` VARCHAR(255) DEFAULT NULL,
  `ISADD` INT DEFAULT NULL,
  `YUYIN` VARCHAR(255) DEFAULT NULL,
  `ISMODIFY` INT DEFAULT NULL,
  `ISDELETE` INT DEFAULT NULL,
  `INCOUNT` INT DEFAULT NULL,
  `ISCOUNT` INT DEFAULT NULL,
  `MODIFYBY` VARCHAR(255) DEFAULT NULL,
  `DATE` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `checkinout_legacy` (
  `USERID` BIGINT DEFAULT NULL,
  `CHECKTIME` DATETIME DEFAULT NULL,
  `CHECKTYPE` VARCHAR(255) DEFAULT NULL,
  `VERIFYCODE` BIGINT DEFAULT NULL,
  `SENSORID` VARCHAR(255) DEFAULT NULL,
  `Memoinfo` VARCHAR(255) DEFAULT NULL,
  `WorkCode` BIGINT DEFAULT NULL,
  `sn` VARCHAR(255) DEFAULT NULL,
  `UserExtFmt` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `departments_legacy` (
  `DEPTID` BIGINT DEFAULT NULL,
  `DEPTNAME` VARCHAR(255) DEFAULT NULL,
  `SUPDEPTID` BIGINT DEFAULT NULL,
  `InheritParentSch` INT DEFAULT NULL,
  `InheritDeptSch` INT DEFAULT NULL,
  `InheritDeptSchClass` INT DEFAULT NULL,
  `AutoSchPlan` INT DEFAULT NULL,
  `InLate` INT DEFAULT NULL,
  `OutEarly` INT DEFAULT NULL,
  `InheritDeptRule` INT DEFAULT NULL,
  `MinAutoSchInterval` BIGINT DEFAULT NULL,
  `RegisterOT` INT DEFAULT NULL,
  `DefaultSchId` BIGINT DEFAULT NULL,
  `ATT` INT DEFAULT NULL,
  `Holiday` INT DEFAULT NULL,
  `OverTime` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EmOpLog` (
  `ID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `OperateTime` DATETIME DEFAULT NULL,
  `manipulationID` BIGINT DEFAULT NULL,
  `Params1` BIGINT DEFAULT NULL,
  `Params2` BIGINT DEFAULT NULL,
  `Params3` BIGINT DEFAULT NULL,
  `Params4` BIGINT DEFAULT NULL,
  `SensorId` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EXCNOTES` (
  `USERID` BIGINT DEFAULT NULL,
  `ATTDATE` DATETIME DEFAULT NULL,
  `NOTES` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `FaceTemp` (
  `TEMPLATEID` BIGINT DEFAULT NULL,
  `USERNO` VARCHAR(255) DEFAULT NULL,
  `SIZE` BIGINT DEFAULT NULL,
  `pin` BIGINT DEFAULT NULL,
  `FACEID` BIGINT DEFAULT NULL,
  `VALID` BIGINT DEFAULT NULL,
  `RESERVE` BIGINT DEFAULT NULL,
  `ACTIVETIME` BIGINT DEFAULT NULL,
  `VFCOUNT` BIGINT DEFAULT NULL,
  `TEMPLATE` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `HOLIDAYS` (
  `HOLIDAYID` BIGINT DEFAULT NULL,
  `HOLIDAYNAME` VARCHAR(255) DEFAULT NULL,
  `HOLIDAYYEAR` INT DEFAULT NULL,
  `HOLIDAYMONTH` INT DEFAULT NULL,
  `HOLIDAYDAY` INT DEFAULT NULL,
  `STARTTIME` DATETIME DEFAULT NULL,
  `DURATION` INT DEFAULT NULL,
  `HOLIDAYTYPE` INT DEFAULT NULL,
  `XINBIE` VARCHAR(255) DEFAULT NULL,
  `MINZU` VARCHAR(255) DEFAULT NULL,
  `DeptID` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `LeaveClass` (
  `LeaveId` BIGINT DEFAULT NULL,
  `LeaveName` VARCHAR(255) DEFAULT NULL,
  `MinUnit` DOUBLE DEFAULT NULL,
  `Unit` INT DEFAULT NULL,
  `RemaindProc` INT DEFAULT NULL,
  `RemaindCount` INT DEFAULT NULL,
  `ReportSymbol` VARCHAR(255) DEFAULT NULL,
  `Deduct` DOUBLE DEFAULT NULL,
  `Color` BIGINT DEFAULT NULL,
  `Classify` INT DEFAULT NULL,
  `Code` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `LeaveClass1` (
  `LeaveId` BIGINT DEFAULT NULL,
  `LeaveName` VARCHAR(255) DEFAULT NULL,
  `MinUnit` DOUBLE DEFAULT NULL,
  `Unit` INT DEFAULT NULL,
  `RemaindProc` INT DEFAULT NULL,
  `RemaindCount` INT DEFAULT NULL,
  `ReportSymbol` VARCHAR(255) DEFAULT NULL,
  `Deduct` DOUBLE DEFAULT NULL,
  `LeaveType` INT DEFAULT NULL,
  `Color` BIGINT DEFAULT NULL,
  `Classify` INT DEFAULT NULL,
  `Calc` TEXT DEFAULT NULL,
  `Code` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Machines` (
  `ID` BIGINT DEFAULT NULL,
  `MachineAlias` VARCHAR(255) DEFAULT NULL,
  `ConnectType` BIGINT DEFAULT NULL,
  `IP` VARCHAR(255) DEFAULT NULL,
  `SerialPort` BIGINT DEFAULT NULL,
  `Port` BIGINT DEFAULT NULL,
  `Baudrate` BIGINT DEFAULT NULL,
  `MachineNumber` BIGINT DEFAULT NULL,
  `IsHost` TINYINT(1) DEFAULT NULL,
  `Enabled` TINYINT(1) DEFAULT NULL,
  `CommPassword` VARCHAR(255) DEFAULT NULL,
  `UILanguage` INT DEFAULT NULL,
  `DateFormat` INT DEFAULT NULL,
  `InOutRecordWarn` INT DEFAULT NULL,
  `Idle` INT DEFAULT NULL,
  `Voice` INT DEFAULT NULL,
  `managercount` INT DEFAULT NULL,
  `usercount` INT DEFAULT NULL,
  `fingercount` INT DEFAULT NULL,
  `SecretCount` INT DEFAULT NULL,
  `FirmwareVersion` VARCHAR(255) DEFAULT NULL,
  `ProductType` VARCHAR(255) DEFAULT NULL,
  `LockControl` INT DEFAULT NULL,
  `Purpose` INT DEFAULT NULL,
  `ProduceKind` BIGINT DEFAULT NULL,
  `sn` VARCHAR(255) DEFAULT NULL,
  `PhotoStamp` VARCHAR(255) DEFAULT NULL,
  `IsIfChangeConfigServer2` BIGINT DEFAULT NULL,
  `pushver` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `NUM_RUN` (
  `NUM_RUNID` BIGINT DEFAULT NULL,
  `OLDID` BIGINT DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  `STARTDATE` DATETIME DEFAULT NULL,
  `ENDDATE` DATETIME DEFAULT NULL,
  `CYLE` INT DEFAULT NULL,
  `UNITS` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `NUM_RUN_DEIL` (
  `NUM_RUNID` INT DEFAULT NULL,
  `STARTTIME` DATETIME DEFAULT NULL,
  `ENDTIME` DATETIME DEFAULT NULL,
  `SDAYS` INT DEFAULT NULL,
  `EDAYS` INT DEFAULT NULL,
  `SCHCLASSID` BIGINT DEFAULT NULL,
  `OverTime` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ReportItem` (
  `RIID` BIGINT DEFAULT NULL,
  `RIIndex` BIGINT DEFAULT NULL,
  `ShowIt` INT DEFAULT NULL,
  `RIName` VARCHAR(255) DEFAULT NULL,
  `UnitName` VARCHAR(255) DEFAULT NULL,
  `Formula` BIGINT DEFAULT NULL,
  `CalcBySchClass` INT DEFAULT NULL,
  `StatisticMethod` INT DEFAULT NULL,
  `CalcLast` INT DEFAULT NULL,
  `Notes` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SchClass` (
  `schClassid` BIGINT DEFAULT NULL,
  `schName` VARCHAR(255) DEFAULT NULL,
  `StartTime` DATETIME DEFAULT NULL,
  `EndTime` DATETIME DEFAULT NULL,
  `LateMinutes` BIGINT DEFAULT NULL,
  `EarlyMinutes` BIGINT DEFAULT NULL,
  `CheckIn` BIGINT DEFAULT NULL,
  `CheckOut` BIGINT DEFAULT NULL,
  `Color` BIGINT DEFAULT NULL,
  `AutoBind` INT DEFAULT NULL,
  `CheckInTime1` DATETIME DEFAULT NULL,
  `CheckInTime2` DATETIME DEFAULT NULL,
  `CheckOutTime1` DATETIME DEFAULT NULL,
  `CheckOutTime2` DATETIME DEFAULT NULL,
  `WorkDay` DOUBLE DEFAULT NULL,
  `SensorID` VARCHAR(255) DEFAULT NULL,
  `WorkMins` DOUBLE DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SECURITYDETAILS` (
  `SECURITYDETAILID` BIGINT DEFAULT NULL,
  `UserId` BIGINT DEFAULT NULL,
  `DEPTID` INT DEFAULT NULL,
  `SCHEDULE` INT DEFAULT NULL,
  `USERINFO` INT DEFAULT NULL,
  `ENROLLFINGERS` INT DEFAULT NULL,
  `REPORTVIEW` INT DEFAULT NULL,
  `REPORT` VARCHAR(255) DEFAULT NULL,
  `ReadOnly` TINYINT(1) DEFAULT NULL,
  `FullControl` TINYINT(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ServerLog` (
  `ID` BIGINT DEFAULT NULL,
  `EVENT` VARCHAR(255) DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `EnrollNumber` VARCHAR(255) DEFAULT NULL,
  `parameter` INT DEFAULT NULL,
  `EVENTTIME` DATETIME DEFAULT NULL,
  `SENSORID` VARCHAR(255) DEFAULT NULL,
  `OPERATOR` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SHIFT` (
  `SHIFTID` BIGINT DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  `USHIFTID` BIGINT DEFAULT NULL,
  `STARTDATE` DATETIME DEFAULT NULL,
  `ENDDATE` DATETIME DEFAULT NULL,
  `RUNNUM` INT DEFAULT NULL,
  `SCH1` BIGINT DEFAULT NULL,
  `SCH2` BIGINT DEFAULT NULL,
  `SCH3` BIGINT DEFAULT NULL,
  `SCH4` BIGINT DEFAULT NULL,
  `SCH5` BIGINT DEFAULT NULL,
  `SCH6` BIGINT DEFAULT NULL,
  `SCH7` BIGINT DEFAULT NULL,
  `SCH8` BIGINT DEFAULT NULL,
  `SCH9` BIGINT DEFAULT NULL,
  `SCH10` BIGINT DEFAULT NULL,
  `SCH11` BIGINT DEFAULT NULL,
  `SCH12` BIGINT DEFAULT NULL,
  `CYCLE` INT DEFAULT NULL,
  `UNITS` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SystemLog` (
  `ID` BIGINT DEFAULT NULL,
  `Operator` VARCHAR(255) DEFAULT NULL,
  `LogTime` DATETIME DEFAULT NULL,
  `MachineAlias` VARCHAR(255) DEFAULT NULL,
  `LogTag` INT DEFAULT NULL,
  `LogDescr` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TBKEY` (
  `PreName` VARCHAR(255) DEFAULT NULL,
  `ONEKEY` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TBSMSALLOT` (
  `REFERENCE` BIGINT DEFAULT NULL,
  `SMSREF` BIGINT DEFAULT NULL,
  `USERREF` BIGINT DEFAULT NULL,
  `GENTM` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TBSMSINFO` (
  `REFERENCE` BIGINT DEFAULT NULL,
  `SMSID` VARCHAR(255) DEFAULT NULL,
  `SMSINDEX` BIGINT DEFAULT NULL,
  `SMSTYPE` BIGINT DEFAULT NULL,
  `SMSCONTENT` TEXT DEFAULT NULL,
  `SMSSTARTTM` VARCHAR(255) DEFAULT NULL,
  `SMSTMLENG` BIGINT DEFAULT NULL,
  `GENTM` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TEMPLATE` (
  `TEMPLATEID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `FINGERID` BIGINT DEFAULT NULL,
  `TEMPLATE` BIGINT DEFAULT NULL,
  `TEMPLATE2` BIGINT DEFAULT NULL,
  `BITMAPPICTURE` BIGINT DEFAULT NULL,
  `BITMAPPICTURE2` BIGINT DEFAULT NULL,
  `BITMAPPICTURE3` BIGINT DEFAULT NULL,
  `BITMAPPICTURE4` BIGINT DEFAULT NULL,
  `USETYPE` INT DEFAULT NULL,
  `EMACHINENUM` VARCHAR(255) DEFAULT NULL,
  `TEMPLATE1` BIGINT DEFAULT NULL,
  `Flag` INT DEFAULT NULL,
  `DivisionFP` INT DEFAULT NULL,
  `TEMPLATE4` BIGINT DEFAULT NULL,
  `TEMPLATE3` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `USER_OF_RUN` (
  `USERID` BIGINT DEFAULT NULL,
  `NUM_OF_RUN_ID` BIGINT DEFAULT NULL,
  `STARTDATE` DATETIME DEFAULT NULL,
  `ENDDATE` DATETIME DEFAULT NULL,
  `ISNOTOF_RUN` BIGINT DEFAULT NULL,
  `ORDER_RUN` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `USER_SPEDAY` (
  `USERID` BIGINT DEFAULT NULL,
  `STARTSPECDAY` DATETIME DEFAULT NULL,
  `ENDSPECDAY` DATETIME DEFAULT NULL,
  `DATEID` INT DEFAULT NULL,
  `YUANYING` VARCHAR(255) DEFAULT NULL,
  `DATE` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `USER_TEMP_SCH` (
  `USERID` BIGINT DEFAULT NULL,
  `COMETIME` DATETIME DEFAULT NULL,
  `LEAVETIME` DATETIME DEFAULT NULL,
  `TYPE` INT DEFAULT NULL,
  `FLAG` INT DEFAULT NULL,
  `SCHCLASSID` BIGINT DEFAULT NULL,
  `OVERTIME` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserACMachines` (
  `UserID` BIGINT DEFAULT NULL,
  `Deviceid` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserACPrivilege` (
  `UserID` BIGINT DEFAULT NULL,
  `DeviceID` BIGINT DEFAULT NULL,
  `ACGroupID` BIGINT DEFAULT NULL,
  `IsUseGroup` TINYINT(1) DEFAULT NULL,
  `TimeZone1` BIGINT DEFAULT NULL,
  `TimeZone2` BIGINT DEFAULT NULL,
  `TimeZone3` BIGINT DEFAULT NULL,
  `verifystyle` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `userinfo` (
  `USERID` BIGINT DEFAULT NULL,
  `Badgenumber` VARCHAR(255) DEFAULT NULL,
  `SSN` VARCHAR(255) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Gender` VARCHAR(255) DEFAULT NULL,
  `TITLE` VARCHAR(255) DEFAULT NULL,
  `PAGER` VARCHAR(255) DEFAULT NULL,
  `BIRTHDAY` DATETIME DEFAULT NULL,
  `HIREDDAY` DATETIME DEFAULT NULL,
  `street` VARCHAR(255) DEFAULT NULL,
  `CITY` VARCHAR(255) DEFAULT NULL,
  `STATE` VARCHAR(255) DEFAULT NULL,
  `ZIP` VARCHAR(255) DEFAULT NULL,
  `OPHONE` VARCHAR(255) DEFAULT NULL,
  `FPHONE` VARCHAR(255) DEFAULT NULL,
  `VERIFICATIONMETHOD` INT DEFAULT NULL,
  `DEFAULTDEPTID` INT DEFAULT NULL,
  `SECURITYFLAGS` INT DEFAULT NULL,
  `ATT` INT DEFAULT NULL,
  `INLATE` INT DEFAULT NULL,
  `OUTEARLY` INT DEFAULT NULL,
  `OVERTIME` INT DEFAULT NULL,
  `SEP` INT DEFAULT NULL,
  `HOLIDAY` INT DEFAULT NULL,
  `MINZU` VARCHAR(255) DEFAULT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  `LUNCHDURATION` INT DEFAULT NULL,
  `PHOTO` BIGINT DEFAULT NULL,
  `mverifypass` VARCHAR(255) DEFAULT NULL,
  `Notes` BIGINT DEFAULT NULL,
  `privilege` BIGINT DEFAULT NULL,
  `InheritDeptSch` INT DEFAULT NULL,
  `InheritDeptSchClass` INT DEFAULT NULL,
  `AutoSchPlan` INT DEFAULT NULL,
  `MinAutoSchInterval` BIGINT DEFAULT NULL,
  `RegisterOT` INT DEFAULT NULL,
  `InheritDeptRule` INT DEFAULT NULL,
  `EMPRIVILEGE` INT DEFAULT NULL,
  `CardNo` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UsersMachines` (
  `ID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `DEVICEID` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserUpdates` (
  `UpdateId` BIGINT DEFAULT NULL,
  `BadgeNumber` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserUsedSClasses` (
  `UserId` BIGINT DEFAULT NULL,
  `SchId` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ZKAttendanceMonthStatistics` (
  `Id` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `PortalSite` BIGINT DEFAULT NULL,
  `Department` BIGINT DEFAULT NULL,
  `Employee` BIGINT DEFAULT NULL,
  `Year` BIGINT DEFAULT NULL,
  `Month` BIGINT DEFAULT NULL,
  `YingDao` DECIMAL(18, 4) DEFAULT NULL,
  `ShiDao` DECIMAL(18, 4) DEFAULT NULL,
  `ChiDao` DECIMAL(18, 4) DEFAULT NULL,
  `ZaoTui` DECIMAL(18, 4) DEFAULT NULL,
  `KuangGong` DECIMAL(18, 4) DEFAULT NULL,
  `JiaBan` DECIMAL(18, 4) DEFAULT NULL,
  `WaiChu` DECIMAL(18, 4) DEFAULT NULL,
  `YinGongWaiChu` DECIMAL(18, 4) DEFAULT NULL,
  `GongZuoShiJian` DECIMAL(18, 4) DEFAULT NULL,
  `YingQian` DECIMAL(18, 4) DEFAULT NULL,
  `QianDao` DECIMAL(18, 4) DEFAULT NULL,
  `QianTui` DECIMAL(18, 4) DEFAULT NULL,
  `WeiQianDao` DECIMAL(18, 4) DEFAULT NULL,
  `WeiQianTui` DECIMAL(18, 4) DEFAULT NULL,
  `QingJia` DECIMAL(18, 4) DEFAULT NULL,
  `PingRi` DECIMAL(18, 4) DEFAULT NULL,
  `ZhouMo` DECIMAL(18, 4) DEFAULT NULL,
  `JieJiaRi` DECIMAL(18, 4) DEFAULT NULL,
  `ChuQinShiJian` DECIMAL(18, 4) DEFAULT NULL,
  `PingRiJiaBan` DECIMAL(18, 4) DEFAULT NULL,
  `ZhouMoJiaBan` DECIMAL(18, 4) DEFAULT NULL,
  `JieJiaRiJiaBan` DECIMAL(18, 4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AttParam` (
  `PARANAME` VARCHAR(255) DEFAULT NULL,
  `PARATYPE` VARCHAR(255) DEFAULT NULL,
  `PARAVALUE` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `DeptUsedSchs` (
  `DeptId` BIGINT DEFAULT NULL,
  `SchId` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ==============================================================================
-- DEFAULT SEED DATA
-- ==============================================================================

-- Default App Users (admin / Admin@2026! and viewer / Viewer@2026!)
INSERT INTO `app_users` (`id`, `username`, `password_hash`, `full_name`, `role`, `is_active`)
VALUES
  (1, 'admin', 'f0ce0e86206541c60bc47be815f83eba98004f63c883e6d71ff5cc929cb5f9ca', 'System Administrator', 'admin', 1),
  (2, 'viewer', '3d869660569bc20cfe40c97a2c77f0953257998c596bbaca03829975a344131e', 'View Only User', 'viewer', 1)
ON DUPLICATE KEY UPDATE
  `password_hash` = VALUES(`password_hash`),
  `full_name` = VALUES(`full_name`),
  `role` = VALUES(`role`),
  `is_active` = VALUES(`is_active`);

-- Default Departments
INSERT INTO `departments` (`dept_id`, `dept_name`)
VALUES
  (1, 'General Registry'),
  (9, 'Marshalls'),
  (10, 'Stenographers'),
  (11, 'Case Management'),
  (12, 'Finance'),
  (13, 'IT'),
  (14, 'General'),
  (15, 'Library')
ON DUPLICATE KEY UPDATE `dept_name` = VALUES(`dept_name`);

-- Default Leave Classes
INSERT INTO `LeaveClass` (`LeaveId`, `LeaveName`, `MinUnit`, `Unit`, `RemaindProc`, `RemaindCount`, `ReportSymbol`, `Deduct`, `Color`, `Classify`, `Code`)
VALUES
  (1, 'Sick', 1, 1, 1, 1, 'B', 0, 3398744, NULL, 'Leave_1'),
  (2, 'Vacation', 1, 1, 1, 1, 'S', 0, 8421631, NULL, 'Leave_2'),
  (3, 'Other', 1, 1, 1, 1, 'T', 0, 16744576, NULL, 'Leave_3')
ON DUPLICATE KEY UPDATE `LeaveName` = VALUES(`LeaveName`);

-- Default Shifts (SchClass)
INSERT INTO `SchClass` (`schClassid`, `schName`, `StartTime`, `EndTime`, `LateMinutes`, `EarlyMinutes`, `CheckIn`, `CheckOut`, `Color`, `AutoBind`, `CheckInTime1`, `CheckInTime2`, `CheckOutTime1`, `CheckOutTime2`, `WorkDay`, `WorkMins`)
VALUES
  (1, 'SC/GR (M)', '1899-12-30 08:00:00', '1899-12-30 12:00:00', 15, 5, 1, 0, 16715535, 1, '1899-12-30 05:00:00', '1899-12-30 11:45:00', '1899-12-30 11:55:00', '1899-12-30 12:30:00', 0.5, 0),
  (2, 'SC/GR (a)', '1899-12-30 13:00:00', '1899-12-30 17:00:00', 15, 10, 0, 1, 8454143, 1, '1899-12-30 12:31:00', '1899-12-30 15:00:00', '1899-12-30 16:50:00', '1899-12-30 22:00:00', 0.5, 0),
  (3, 'SG/GR (F)', '1899-12-30 13:00:00', '1899-12-30 16:30:00', 15, 10, 0, 1, 255, 1, '1899-12-30 12:31:00', '1899-12-30 15:00:00', '1899-12-30 16:20:00', '1899-12-30 22:00:00', 0.5, 0),
  (4, 'NEW-(A)', '1899-12-30 07:00:00', '1899-12-30 10:00:00', 15, 10, 1, 1, 16744448, 1, '1899-12-30 06:00:00', '1899-12-30 08:00:00', '1899-12-30 09:00:00', '1899-12-30 12:00:00', 0.5, 0),
  (5, 'New-(P)', '1899-12-30 13:00:00', '1899-12-30 19:00:00', 15, 10, 1, 1, 65280, 1, '1899-12-30 12:00:00', '1899-12-30 14:00:00', '1899-12-30 18:00:00', '1899-12-30 21:00:00', 0.5, 0)
ON DUPLICATE KEY UPDATE `schName` = VALUES(`schName`);

-- Default Schedule Rotations (NUM_RUN)
INSERT INTO `NUM_RUN` (`NUM_RUNID`, `OLDID`, `NAME`, `STARTDATE`, `ENDDATE`, `CYLE`, `UNITS`)
VALUES
  (1, -1, 'SC/GR', '2013-01-01 00:00:00', '2200-12-31 00:00:00', 1, 1),
  (2, -1, 'New Shift', '2018-11-01 00:00:00', '2200-12-31 00:00:00', 1, 1)
ON DUPLICATE KEY UPDATE `NAME` = VALUES(`NAME`);

-- Default Registered Devices
INSERT INTO `devices` (`id`, `sn`, `alias`, `ip_address`, `model`, `status`)
VALUES
  (2, '3355300480195', 'CLOCKOLD', '192.168.0.13', 'ZKTeco', 'active'),
  (3, 'KWQ3241600155', 'GenReg1', '10.10.61.2', 'ZKTeco', 'active'),
  (4, 'KWQ3241600076', '6', '10.10.61.3', 'ZKTeco', 'active'),
  (5, 'KWQ3241600103', 'CLOCK2', '192.168.0.71', 'ZKTeco', 'active'),
  (6, 'KWQ3241600105', 'CLOCK3', '192.168.0.72', 'ZKTeco', 'active'),
  (7, 'KWQ3241600153', 'CLOCK4', '192.168.0.73', 'ZKTeco', 'active')
ON DUPLICATE KEY UPDATE
  `alias` = VALUES(`alias`),
  `ip_address` = VALUES(`ip_address`),
  `status` = VALUES(`status`);

SET FOREIGN_KEY_CHECKS = 1;
