-- Complete Schema for TimeClock Attendance System (All Tables)
-- Auto-generated from att2000.mdb and TimePulse application
CREATE DATABASE IF NOT EXISTS timeclock_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE timeclock_db;

CREATE TABLE IF NOT EXISTS `ACGroup` (
  `GroupID` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `TimeZone1` INT DEFAULT NULL,
  `TimeZone2` INT DEFAULT NULL,
  `TimeZone3` INT DEFAULT NULL,
  `holidayvaild` TINYINT(1) DEFAULT NULL,
  `verifystyle` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `acholiday` (
  `primaryid` BIGINT DEFAULT NULL,
  `holidayid` BIGINT DEFAULT NULL,
  `begindate` DATETIME DEFAULT NULL,
  `enddate` DATETIME DEFAULT NULL,
  `timezone` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ACTimeZones` (
  `TimeZoneID` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `SunStart` DATETIME DEFAULT NULL,
  `SunEnd` DATETIME DEFAULT NULL,
  `MonStart` DATETIME DEFAULT NULL,
  `MonEnd` DATETIME DEFAULT NULL,
  `TuesStart` DATETIME DEFAULT NULL,
  `TuesEnd` DATETIME DEFAULT NULL,
  `WedStart` DATETIME DEFAULT NULL,
  `WedEnd` DATETIME DEFAULT NULL,
  `ThursStart` DATETIME DEFAULT NULL,
  `ThursEnd` DATETIME DEFAULT NULL,
  `FriStart` DATETIME DEFAULT NULL,
  `FriEnd` DATETIME DEFAULT NULL,
  `SatStart` DATETIME DEFAULT NULL,
  `SatEnd` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ACUnlockComb` (
  `UnlockCombID` INT DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Group01` INT DEFAULT NULL,
  `Group02` INT DEFAULT NULL,
  `Group03` INT DEFAULT NULL,
  `Group04` INT DEFAULT NULL,
  `Group05` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AlarmLog` (
  `ID` BIGINT DEFAULT NULL,
  `Operator` VARCHAR(255) DEFAULT NULL,
  `EnrollNumber` VARCHAR(255) DEFAULT NULL,
  `LogTime` DATETIME DEFAULT NULL,
  `MachineAlias` VARCHAR(255) DEFAULT NULL,
  `AlarmType` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AuditedExc` (
  `AEID` BIGINT DEFAULT NULL,
  `UserId` BIGINT DEFAULT NULL,
  `CheckTime` DATETIME DEFAULT NULL,
  `NewExcID` BIGINT DEFAULT NULL,
  `IsLeave` INT DEFAULT NULL,
  `UName` VARCHAR(255) DEFAULT NULL,
  `UTime` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AUTHDEVICE` (
  `ID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `MachineID` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `CHECKEXACT` (
  `EXACTID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `CHECKTIME` DATETIME DEFAULT NULL,
  `CHECKTYPE` VARCHAR(255) DEFAULT NULL,
  `ISADD` INT DEFAULT NULL,
  `YUYIN` VARCHAR(255) DEFAULT NULL,
  `ISMODIFY` INT DEFAULT NULL,
  `ISDELETE` INT DEFAULT NULL,
  `INCOUNT` INT DEFAULT NULL,
  `ISCOUNT` INT DEFAULT NULL,
  `MODIFYBY` VARCHAR(255) DEFAULT NULL,
  `DATE` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `checkinout_legacy` (
  `USERID` BIGINT DEFAULT NULL,
  `CHECKTIME` DATETIME DEFAULT NULL,
  `CHECKTYPE` VARCHAR(255) DEFAULT NULL,
  `VERIFYCODE` BIGINT DEFAULT NULL,
  `SENSORID` VARCHAR(255) DEFAULT NULL,
  `Memoinfo` VARCHAR(255) DEFAULT NULL,
  `WorkCode` BIGINT DEFAULT NULL,
  `sn` VARCHAR(255) DEFAULT NULL,
  `UserExtFmt` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `departments_legacy` (
  `DEPTID` BIGINT DEFAULT NULL,
  `DEPTNAME` VARCHAR(255) DEFAULT NULL,
  `SUPDEPTID` BIGINT DEFAULT NULL,
  `InheritParentSch` INT DEFAULT NULL,
  `InheritDeptSch` INT DEFAULT NULL,
  `InheritDeptSchClass` INT DEFAULT NULL,
  `AutoSchPlan` INT DEFAULT NULL,
  `InLate` INT DEFAULT NULL,
  `OutEarly` INT DEFAULT NULL,
  `InheritDeptRule` INT DEFAULT NULL,
  `MinAutoSchInterval` BIGINT DEFAULT NULL,
  `RegisterOT` INT DEFAULT NULL,
  `DefaultSchId` BIGINT DEFAULT NULL,
  `ATT` INT DEFAULT NULL,
  `Holiday` INT DEFAULT NULL,
  `OverTime` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EmOpLog` (
  `ID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `OperateTime` DATETIME DEFAULT NULL,
  `manipulationID` BIGINT DEFAULT NULL,
  `Params1` BIGINT DEFAULT NULL,
  `Params2` BIGINT DEFAULT NULL,
  `Params3` BIGINT DEFAULT NULL,
  `Params4` BIGINT DEFAULT NULL,
  `SensorId` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EXCNOTES` (
  `USERID` BIGINT DEFAULT NULL,
  `ATTDATE` DATETIME DEFAULT NULL,
  `NOTES` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `FaceTemp` (
  `TEMPLATEID` BIGINT DEFAULT NULL,
  `USERNO` VARCHAR(255) DEFAULT NULL,
  `SIZE` BIGINT DEFAULT NULL,
  `pin` BIGINT DEFAULT NULL,
  `FACEID` BIGINT DEFAULT NULL,
  `VALID` BIGINT DEFAULT NULL,
  `RESERVE` BIGINT DEFAULT NULL,
  `ACTIVETIME` BIGINT DEFAULT NULL,
  `VFCOUNT` BIGINT DEFAULT NULL,
  `TEMPLATE` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `HOLIDAYS` (
  `HOLIDAYID` BIGINT DEFAULT NULL,
  `HOLIDAYNAME` VARCHAR(255) DEFAULT NULL,
  `HOLIDAYYEAR` INT DEFAULT NULL,
  `HOLIDAYMONTH` INT DEFAULT NULL,
  `HOLIDAYDAY` INT DEFAULT NULL,
  `STARTTIME` DATETIME DEFAULT NULL,
  `DURATION` INT DEFAULT NULL,
  `HOLIDAYTYPE` INT DEFAULT NULL,
  `XINBIE` VARCHAR(255) DEFAULT NULL,
  `MINZU` VARCHAR(255) DEFAULT NULL,
  `DeptID` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `LeaveClass` (
  `LeaveId` BIGINT DEFAULT NULL,
  `LeaveName` VARCHAR(255) DEFAULT NULL,
  `MinUnit` DOUBLE DEFAULT NULL,
  `Unit` INT DEFAULT NULL,
  `RemaindProc` INT DEFAULT NULL,
  `RemaindCount` INT DEFAULT NULL,
  `ReportSymbol` VARCHAR(255) DEFAULT NULL,
  `Deduct` DOUBLE DEFAULT NULL,
  `Color` BIGINT DEFAULT NULL,
  `Classify` INT DEFAULT NULL,
  `Code` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `LeaveClass1` (
  `LeaveId` BIGINT DEFAULT NULL,
  `LeaveName` VARCHAR(255) DEFAULT NULL,
  `MinUnit` DOUBLE DEFAULT NULL,
  `Unit` INT DEFAULT NULL,
  `RemaindProc` INT DEFAULT NULL,
  `RemaindCount` INT DEFAULT NULL,
  `ReportSymbol` VARCHAR(255) DEFAULT NULL,
  `Deduct` DOUBLE DEFAULT NULL,
  `LeaveType` INT DEFAULT NULL,
  `Color` BIGINT DEFAULT NULL,
  `Classify` INT DEFAULT NULL,
  `Calc` TEXT DEFAULT NULL,
  `Code` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Machines` (
  `ID` BIGINT DEFAULT NULL,
  `MachineAlias` VARCHAR(255) DEFAULT NULL,
  `ConnectType` BIGINT DEFAULT NULL,
  `IP` VARCHAR(255) DEFAULT NULL,
  `SerialPort` BIGINT DEFAULT NULL,
  `Port` BIGINT DEFAULT NULL,
  `Baudrate` BIGINT DEFAULT NULL,
  `MachineNumber` BIGINT DEFAULT NULL,
  `IsHost` TINYINT(1) DEFAULT NULL,
  `Enabled` TINYINT(1) DEFAULT NULL,
  `CommPassword` VARCHAR(255) DEFAULT NULL,
  `UILanguage` INT DEFAULT NULL,
  `DateFormat` INT DEFAULT NULL,
  `InOutRecordWarn` INT DEFAULT NULL,
  `Idle` INT DEFAULT NULL,
  `Voice` INT DEFAULT NULL,
  `managercount` INT DEFAULT NULL,
  `usercount` INT DEFAULT NULL,
  `fingercount` INT DEFAULT NULL,
  `SecretCount` INT DEFAULT NULL,
  `FirmwareVersion` VARCHAR(255) DEFAULT NULL,
  `ProductType` VARCHAR(255) DEFAULT NULL,
  `LockControl` INT DEFAULT NULL,
  `Purpose` INT DEFAULT NULL,
  `ProduceKind` BIGINT DEFAULT NULL,
  `sn` VARCHAR(255) DEFAULT NULL,
  `PhotoStamp` VARCHAR(255) DEFAULT NULL,
  `IsIfChangeConfigServer2` BIGINT DEFAULT NULL,
  `pushver` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `NUM_RUN` (
  `NUM_RUNID` BIGINT DEFAULT NULL,
  `OLDID` BIGINT DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  `STARTDATE` DATETIME DEFAULT NULL,
  `ENDDATE` DATETIME DEFAULT NULL,
  `CYLE` INT DEFAULT NULL,
  `UNITS` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `NUM_RUN_DEIL` (
  `NUM_RUNID` INT DEFAULT NULL,
  `STARTTIME` DATETIME DEFAULT NULL,
  `ENDTIME` DATETIME DEFAULT NULL,
  `SDAYS` INT DEFAULT NULL,
  `EDAYS` INT DEFAULT NULL,
  `SCHCLASSID` BIGINT DEFAULT NULL,
  `OverTime` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ReportItem` (
  `RIID` BIGINT DEFAULT NULL,
  `RIIndex` BIGINT DEFAULT NULL,
  `ShowIt` INT DEFAULT NULL,
  `RIName` VARCHAR(255) DEFAULT NULL,
  `UnitName` VARCHAR(255) DEFAULT NULL,
  `Formula` BIGINT DEFAULT NULL,
  `CalcBySchClass` INT DEFAULT NULL,
  `StatisticMethod` INT DEFAULT NULL,
  `CalcLast` INT DEFAULT NULL,
  `Notes` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SchClass` (
  `schClassid` BIGINT DEFAULT NULL,
  `schName` VARCHAR(255) DEFAULT NULL,
  `StartTime` DATETIME DEFAULT NULL,
  `EndTime` DATETIME DEFAULT NULL,
  `LateMinutes` BIGINT DEFAULT NULL,
  `EarlyMinutes` BIGINT DEFAULT NULL,
  `CheckIn` BIGINT DEFAULT NULL,
  `CheckOut` BIGINT DEFAULT NULL,
  `Color` BIGINT DEFAULT NULL,
  `AutoBind` INT DEFAULT NULL,
  `CheckInTime1` DATETIME DEFAULT NULL,
  `CheckInTime2` DATETIME DEFAULT NULL,
  `CheckOutTime1` DATETIME DEFAULT NULL,
  `CheckOutTime2` DATETIME DEFAULT NULL,
  `WorkDay` DOUBLE DEFAULT NULL,
  `SensorID` VARCHAR(255) DEFAULT NULL,
  `WorkMins` DOUBLE DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SECURITYDETAILS` (
  `SECURITYDETAILID` BIGINT DEFAULT NULL,
  `UserId` BIGINT DEFAULT NULL,
  `DEPTID` INT DEFAULT NULL,
  `SCHEDULE` INT DEFAULT NULL,
  `USERINFO` INT DEFAULT NULL,
  `ENROLLFINGERS` INT DEFAULT NULL,
  `REPORTVIEW` INT DEFAULT NULL,
  `REPORT` VARCHAR(255) DEFAULT NULL,
  `ReadOnly` TINYINT(1) DEFAULT NULL,
  `FullControl` TINYINT(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ServerLog` (
  `ID` BIGINT DEFAULT NULL,
  `EVENT` VARCHAR(255) DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `EnrollNumber` VARCHAR(255) DEFAULT NULL,
  `parameter` INT DEFAULT NULL,
  `EVENTTIME` DATETIME DEFAULT NULL,
  `SENSORID` VARCHAR(255) DEFAULT NULL,
  `OPERATOR` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SHIFT` (
  `SHIFTID` BIGINT DEFAULT NULL,
  `NAME` VARCHAR(255) DEFAULT NULL,
  `USHIFTID` BIGINT DEFAULT NULL,
  `STARTDATE` DATETIME DEFAULT NULL,
  `ENDDATE` DATETIME DEFAULT NULL,
  `RUNNUM` INT DEFAULT NULL,
  `SCH1` BIGINT DEFAULT NULL,
  `SCH2` BIGINT DEFAULT NULL,
  `SCH3` BIGINT DEFAULT NULL,
  `SCH4` BIGINT DEFAULT NULL,
  `SCH5` BIGINT DEFAULT NULL,
  `SCH6` BIGINT DEFAULT NULL,
  `SCH7` BIGINT DEFAULT NULL,
  `SCH8` BIGINT DEFAULT NULL,
  `SCH9` BIGINT DEFAULT NULL,
  `SCH10` BIGINT DEFAULT NULL,
  `SCH11` BIGINT DEFAULT NULL,
  `SCH12` BIGINT DEFAULT NULL,
  `CYCLE` INT DEFAULT NULL,
  `UNITS` INT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SystemLog` (
  `ID` BIGINT DEFAULT NULL,
  `Operator` VARCHAR(255) DEFAULT NULL,
  `LogTime` DATETIME DEFAULT NULL,
  `MachineAlias` VARCHAR(255) DEFAULT NULL,
  `LogTag` INT DEFAULT NULL,
  `LogDescr` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TBKEY` (
  `PreName` VARCHAR(255) DEFAULT NULL,
  `ONEKEY` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TBSMSALLOT` (
  `REFERENCE` BIGINT DEFAULT NULL,
  `SMSREF` BIGINT DEFAULT NULL,
  `USERREF` BIGINT DEFAULT NULL,
  `GENTM` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TBSMSINFO` (
  `REFERENCE` BIGINT DEFAULT NULL,
  `SMSID` VARCHAR(255) DEFAULT NULL,
  `SMSINDEX` BIGINT DEFAULT NULL,
  `SMSTYPE` BIGINT DEFAULT NULL,
  `SMSCONTENT` TEXT DEFAULT NULL,
  `SMSSTARTTM` VARCHAR(255) DEFAULT NULL,
  `SMSTMLENG` BIGINT DEFAULT NULL,
  `GENTM` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TEMPLATE` (
  `TEMPLATEID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `FINGERID` BIGINT DEFAULT NULL,
  `TEMPLATE` BIGINT DEFAULT NULL,
  `TEMPLATE2` BIGINT DEFAULT NULL,
  `BITMAPPICTURE` BIGINT DEFAULT NULL,
  `BITMAPPICTURE2` BIGINT DEFAULT NULL,
  `BITMAPPICTURE3` BIGINT DEFAULT NULL,
  `BITMAPPICTURE4` BIGINT DEFAULT NULL,
  `USETYPE` INT DEFAULT NULL,
  `EMACHINENUM` VARCHAR(255) DEFAULT NULL,
  `TEMPLATE1` BIGINT DEFAULT NULL,
  `Flag` INT DEFAULT NULL,
  `DivisionFP` INT DEFAULT NULL,
  `TEMPLATE4` BIGINT DEFAULT NULL,
  `TEMPLATE3` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `USER_OF_RUN` (
  `USERID` BIGINT DEFAULT NULL,
  `NUM_OF_RUN_ID` BIGINT DEFAULT NULL,
  `STARTDATE` DATETIME DEFAULT NULL,
  `ENDDATE` DATETIME DEFAULT NULL,
  `ISNOTOF_RUN` BIGINT DEFAULT NULL,
  `ORDER_RUN` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `USER_SPEDAY` (
  `USERID` BIGINT DEFAULT NULL,
  `STARTSPECDAY` DATETIME DEFAULT NULL,
  `ENDSPECDAY` DATETIME DEFAULT NULL,
  `DATEID` INT DEFAULT NULL,
  `YUANYING` VARCHAR(255) DEFAULT NULL,
  `DATE` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `USER_TEMP_SCH` (
  `USERID` BIGINT DEFAULT NULL,
  `COMETIME` DATETIME DEFAULT NULL,
  `LEAVETIME` DATETIME DEFAULT NULL,
  `TYPE` INT DEFAULT NULL,
  `FLAG` INT DEFAULT NULL,
  `SCHCLASSID` BIGINT DEFAULT NULL,
  `OVERTIME` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserACMachines` (
  `UserID` BIGINT DEFAULT NULL,
  `Deviceid` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserACPrivilege` (
  `UserID` BIGINT DEFAULT NULL,
  `DeviceID` BIGINT DEFAULT NULL,
  `ACGroupID` BIGINT DEFAULT NULL,
  `IsUseGroup` TINYINT(1) DEFAULT NULL,
  `TimeZone1` BIGINT DEFAULT NULL,
  `TimeZone2` BIGINT DEFAULT NULL,
  `TimeZone3` BIGINT DEFAULT NULL,
  `verifystyle` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `userinfo` (
  `USERID` BIGINT DEFAULT NULL,
  `Badgenumber` VARCHAR(255) DEFAULT NULL,
  `SSN` VARCHAR(255) DEFAULT NULL,
  `Name` VARCHAR(255) DEFAULT NULL,
  `Gender` VARCHAR(255) DEFAULT NULL,
  `TITLE` VARCHAR(255) DEFAULT NULL,
  `PAGER` VARCHAR(255) DEFAULT NULL,
  `BIRTHDAY` DATETIME DEFAULT NULL,
  `HIREDDAY` DATETIME DEFAULT NULL,
  `street` VARCHAR(255) DEFAULT NULL,
  `CITY` VARCHAR(255) DEFAULT NULL,
  `STATE` VARCHAR(255) DEFAULT NULL,
  `ZIP` VARCHAR(255) DEFAULT NULL,
  `OPHONE` VARCHAR(255) DEFAULT NULL,
  `FPHONE` VARCHAR(255) DEFAULT NULL,
  `VERIFICATIONMETHOD` INT DEFAULT NULL,
  `DEFAULTDEPTID` INT DEFAULT NULL,
  `SECURITYFLAGS` INT DEFAULT NULL,
  `ATT` INT DEFAULT NULL,
  `INLATE` INT DEFAULT NULL,
  `OUTEARLY` INT DEFAULT NULL,
  `OVERTIME` INT DEFAULT NULL,
  `SEP` INT DEFAULT NULL,
  `HOLIDAY` INT DEFAULT NULL,
  `MINZU` VARCHAR(255) DEFAULT NULL,
  `PASSWORD` VARCHAR(255) DEFAULT NULL,
  `LUNCHDURATION` INT DEFAULT NULL,
  `PHOTO` BIGINT DEFAULT NULL,
  `mverifypass` VARCHAR(255) DEFAULT NULL,
  `Notes` BIGINT DEFAULT NULL,
  `privilege` BIGINT DEFAULT NULL,
  `InheritDeptSch` INT DEFAULT NULL,
  `InheritDeptSchClass` INT DEFAULT NULL,
  `AutoSchPlan` INT DEFAULT NULL,
  `MinAutoSchInterval` BIGINT DEFAULT NULL,
  `RegisterOT` INT DEFAULT NULL,
  `InheritDeptRule` INT DEFAULT NULL,
  `EMPRIVILEGE` INT DEFAULT NULL,
  `CardNo` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UsersMachines` (
  `ID` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `DEVICEID` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserUpdates` (
  `UpdateId` BIGINT DEFAULT NULL,
  `BadgeNumber` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `UserUsedSClasses` (
  `UserId` BIGINT DEFAULT NULL,
  `SchId` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ZKAttendanceMonthStatistics` (
  `Id` BIGINT DEFAULT NULL,
  `USERID` BIGINT DEFAULT NULL,
  `PortalSite` BIGINT DEFAULT NULL,
  `Department` BIGINT DEFAULT NULL,
  `Employee` BIGINT DEFAULT NULL,
  `Year` BIGINT DEFAULT NULL,
  `Month` BIGINT DEFAULT NULL,
  `YingDao` DECIMAL(18, 4) DEFAULT NULL,
  `ShiDao` DECIMAL(18, 4) DEFAULT NULL,
  `ChiDao` DECIMAL(18, 4) DEFAULT NULL,
  `ZaoTui` DECIMAL(18, 4) DEFAULT NULL,
  `KuangGong` DECIMAL(18, 4) DEFAULT NULL,
  `JiaBan` DECIMAL(18, 4) DEFAULT NULL,
  `WaiChu` DECIMAL(18, 4) DEFAULT NULL,
  `YinGongWaiChu` DECIMAL(18, 4) DEFAULT NULL,
  `GongZuoShiJian` DECIMAL(18, 4) DEFAULT NULL,
  `YingQian` DECIMAL(18, 4) DEFAULT NULL,
  `QianDao` DECIMAL(18, 4) DEFAULT NULL,
  `QianTui` DECIMAL(18, 4) DEFAULT NULL,
  `WeiQianDao` DECIMAL(18, 4) DEFAULT NULL,
  `WeiQianTui` DECIMAL(18, 4) DEFAULT NULL,
  `QingJia` DECIMAL(18, 4) DEFAULT NULL,
  `PingRi` DECIMAL(18, 4) DEFAULT NULL,
  `ZhouMo` DECIMAL(18, 4) DEFAULT NULL,
  `JieJiaRi` DECIMAL(18, 4) DEFAULT NULL,
  `ChuQinShiJian` DECIMAL(18, 4) DEFAULT NULL,
  `PingRiJiaBan` DECIMAL(18, 4) DEFAULT NULL,
  `ZhouMoJiaBan` DECIMAL(18, 4) DEFAULT NULL,
  `JieJiaRiJiaBan` DECIMAL(18, 4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AttParam` (
  `PARANAME` VARCHAR(255) DEFAULT NULL,
  `PARATYPE` VARCHAR(255) DEFAULT NULL,
  `PARAVALUE` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `DeptUsedSchs` (
  `DeptId` BIGINT DEFAULT NULL,
  `SchId` BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

